config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  get "intro" => "home#intro", as: :intro

  resources :profiles do
    resources :quotes
  end
  resources :committees
  resources :groups
  resources :teachers do
    resources :quotes
  end

  resources :announcements

  resources :votings do
    resources :voting_options
    resources :votes
    resources :awards do
      resources :nominations
    end
  end
  
  resources :content_problems
  
  resources :questions do
    resources :answers
  end

  resources :products
  resources :orders do
    resource :ticket
  end
  post "orders/shipping" => "orders#shipping", as: :order_shipping
  patch "orders/:id/paid" => "orders#paid", as: :mark_order_as_paid
  
  get "orders/:token/delivery" => "orders#delivery", as: :plan_delivery
  get "orders/:token/delivery/invalid" => "orders#invalid_delivery", as: :invalid_delivery
  get "orders/:token/delivery/success" => "orders#delivery_success", as: :delivery_success
  post "orders/:token/delivery" => "orders#save_delivery", as: :create_delivery_address

   
  resources :tickets

  get "tickets/info/delegate" => "tickets#delegate", as: :delegate_ticket

  resources :contents

  get "votings/:voting_id/voting_options/:option_id/select" => "voting_options#select", as: :select_voting_option
  get "votings/:voting_id/voting_options/:option_id/deselect" => "voting_options#deselect", as: :deselect_voting_option
  get "votings/:voting_id/votes/:vote_id/lock" => "votes#lock", as: :lock_vote
  get "votings/:voting_id/votes/new/selective/:max_choices" => "votes#new_selection", as: :new_selective_votes
  get "votings/:voting_id/results" => "votings#results", as: :voting_results
  delete "votings/:voting_id/cleanup" => "voting_options#cleanup", as: :cleanup_voting

  get "votings/:voting_id/awards/:award_id/nominate" => "awards#nominate", as: :nominate_for_awards

  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/accept" => "nominations#accept", as: :accept_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/dismiss" => "nominations#dismiss", as: :dismiss_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/reset" => "nominations#reset", as: :reset_nomination

  get "notifications/:user_id/stop/:stop_key" => "users#stop_notifications", as: :stop_notifications

  get "votes/validate" => "votes#validate_vote", as: :vote_validation
  post "votes/validate" => "votes#validate", as: :validate_vote

  get "contents/new/thanks" => "contents#complete", as: :content_complete

  delete "users/:id" => "users#destroy", as: :user

  get "quotes/approve" => "quotes#show_pending", as: :pending_quotes

  get "eintragen" => "student_registration#new"
  post "eintragen" => "student_registration#create"
  get "eintragen/abgeschlossen" => "student_registration#finished", as: :finished_registration

  post "profiles/:profile_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_profile_quote
  post "teachers/:teacher_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_teacher_quote

  patch "profiles/:profile_id/quotes/:quote_id/edit" => "quotes#update", as: :update_profile_quote

  get "committees/:id/participate" => "committees#prepare_participation", as: :prepare_participation
  post "committees/:id/participate" => "committees#participate", as: :participate
  delete "committees/:id/participate" => "committees#departicipate", as: :departicipate

  post "users/identity/disassociate" => "users#remove_association", as: :remove_association
  get "users/invited" => "users#list_invited", as: :invited_users
  get "users/become" => "users#become", as: :become_user
  post "users/become" => "users#become_user", as: :sign_in_as_user
  
  get "validations/:token" => "validations#index", as: :main_validations
  get "validations/:token/comments" => "validations#comments", as: :validate_comments
  get "validations/:token/contents" => "validations#contents", as: :validate_contents
  get "validations/:token/questions" => "validations#questions", as: :validate_questions
  get "validations/:token/contents/:content_id/report" => "validations#report_content", as: :report_content
  post "validations/:token/contents/:content_id/report" => "validations#create_report", as: :create_content_problem
  
  get "validations/:token/questions/:question_id/answers/new" => "validations#new_answer", as: :new_validation_answer
  get "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#edit_answer", as: :edit_validation_answer
  patch "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#update_answer", as: :update_validation_answer
  post "validations/:token/questions/:question_id/answers/new" => "validations#create_answer", as: :create_validation_answer
  
  post "validations/:token/quick_order" => "validations#quick_order", as: :create_quick_order
  
  get "validations/:token/final" => "validations#final", as: :validation_final
  get "validations/:token/preview" => "validations#preview", as: :validation_preview
  
  post "content_problems/:id/accept" => "content_problems#accept", as: :accept_report
  get "content_problems/:id/reject" => "content_problems#prepare_rejection", as: :prepare_report_rejection
  post "content_problems/:id/reject" => "content_problems#reject", as: :reject_report
  
  post "validations/:token/change_name" => "validations#change_name", as: :validation_change_name
  
  patch "validations/:token/comments/:comment_id/lock" => "validations#lock_comment", as: :lock_comment
  get "tokens" => "validations#access_tokens", as: :access_tokens
  post "tokens/new" => "validations#create_single_token", as: :create_single_token
  get "validations/:token/wrong_identity" => "validations#wrong_identity", as: :validation_wrong_identity
  get "validations/:token/error" => "validations#fatal_error", as: :validation_error
  get "validations/:token/invalid" => "validations#invalid", as: :invalid_token
  
  get "contents/:content_id/association/new" => "contents#new_association", as: :new_content_association
  post "contents/:content_id/association/new" => "contents#create_association", as: :create_content_association
  delete "contents/:content_id/association/:assoc_id" => "contents#destroy_association", as: :destroy_content_association
  
  get "tickets/orders/new" => "tickets#new_order", as: :new_ticket_order
  get "tickets/:id/download" => "tickets#download", as: :download_ticket

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :user
  has_many :content_associations
  has_many :content_problems

  has_attached_file :file
  do_not_validate_attachment_file_type :file
  validates_attachment_size :file, :less_than => 10.megabytes

  validates :title, :kind, presence: true
  
  def self.export_all
    require 'csv'
    csv_path = "#{Rails.root}/export/contents.csv"
    
    #contents = Content.joins(:content_problems).where.not(content_problems: { legit: true }).includes(:content_associations)
    contents = Content.includes(:content_problems).includes(:content_associations).all

    CSV.open(csv_path, "wb") do |csv|
      csv << ["id", "title", "kind", "text", "associations", "problem", "legit", "reason", "description"]
      contents.each do |content|
        row = [content.id, content.title, content.kind, content.text]
        row << content.content_associations.map {|assoc| Profile.find(assoc.profile_id).full_name}
        row << content.content_problems.map {|p| true}
        row << content.content_problems.map {|p| p.legit}
        row << content.content_problems.map {|p| p.reason}
        row << content.content_problems.map {|p| p.description}
        csv << row
      end
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_profile!

  respond_to :html, :json

  def new
  end
  
  def new_association
    authorize :content, :create_association?
    
    @association = ContentAssociation.new
  end
  
  def create_association
    authorize :content, :create_association?
    
    content = Content.find(params[:content_id])
    profile = Profile.find(params[:content_association][:profile_id])
    @association = ContentAssociation.create(content: content, profile: profile)
    redirect_to content
  end
  
  def destroy_association
    authorize :content, :create_association?
    
    @association = ContentAssociation.find(params[:assoc_id])
    @association.destroy
    redirect_to Content.find(params[:content_id])
  end

  def create
    authorize :content, :create?

    @content = Content.new(content_params)
    @content.user = current_user

    if @content.save
      redirect_to content_complete_path
    else
      flash[:notice] = "Fehler beim Speichern. Bitte stelle sicher, dass alle erforderlichen Felder ausgefüllt sind. Dateien dürfen max. 10 MB groß sein. Möchtest du größere Dateien bereitstellen, kontaktiere uns."
      render :new
    end
  end

  def index
    authorize :content, :index?

    @contents = Content.all

    respond_to do |format|
      format.html
      format.json { render json: ContentDatatable.new(view_context) }
    end
  end

  def show
    @content = Content.find(params[:id])
    authorize @content
  end

  def edit
    if @content = Content.find(params[:id])
      authorize @content
    else
      redirect_to root_url, alert: "Inhalt nicht gefunden."
    end
  end

  def update
    @content = Content.find(params[:id])
    authorize @content

    if @content.update(content_params)
      redirect_to @content
    else
      render :edit
    end
  end

  def destroy
    @content = Content.find(params[:id])
    authorize @content

    if @content.destroy
      redirect_to contents_path, notice: "Inhalt gelöscht."
    else
      render :show
    end
  end

  def complete
    render :complete
  end

  private

  def content_params
    params.require(:content).permit(:title, :text, :kind, :file)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<%= content.title %>
<%= content.file %>

app/views/contents/complete.html.erb
<h3>Vielen Dank!</h3>
<p>Deine Einreichung wurde an uns übermittelt.</p>
<%= link_to raw("&laquo; Zurück zum Dashboard"), root_url, class: 'btn btn-primary' %>

app/views/contents/edit.html.erb
<%= simple_form_for(@content, method: :patch) do |f| %>
<%= f.input :title %>
<%= f.input :kind %>
<%= f.input :text, label: "Beschreibung (nutze für längere Texte den Dateiupload)"  %>
<%= f.file_field :file %>
<%= f.button :submit %>
<% end %>
<%= render partial: 'admin/deletable', locals: {model_name: "Inhalt", path: content_path(@content), hide_ruler: false} %>

app/views/contents/index.html.erb
<table id="contents-table" class="table table-striped table-bordered" data-source="<%= contents_path(format: :json) %>">
  <thead>
    <tr>
      <th>Titel</th>
      <th>Typ</th>
      <th>letzte Änderung</th>
      <th>Aktion</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/contents/new.html.erb
<%= simple_form_for :content, url: {action: 'create'}, :html => { :multipart => true } do |f| %>
  <h3>Einen Inhalt einreichen</h3>
  <p>Danke, dass du an der Erstellung der Abizeitung mitwirken möchtest. Über dieses Formular kannst du einen Inhalt, den du selbst erstellt hast, oder ein denkwürdiges Zitat einreichen.</p>
  <p>Nutze das Titelfeld für eine aussagekräftige Beschreibung. Halte dich bei Zitaten bitte an die Konvention "Kurs: Lehrkraft".</p>
  <%= f.input :title, label: 'Titel (z.B. "Bio-LK: Niehaus" bei einem Zitat)' %>
  <%= f.input :kind, label: "Art (z.B. Zitat, Foto, Karikatur, ...)" %>
  <p>Nutze das Textfeld für deinen Inhalt. Stelle bei Zitaten sicher, dass sich der Kontext der Aussage aus deiner Darstellung ergibt. Stelle sicher, dass die Urheberschaft deutlich wird. Bitte nutze für besonders lange Inhalte oder Inhalte mit Bildern den Dateiupload.</p>
  <%= f.input :text, as: :text, label: "Text (nutze für größere Inhalte den Dateiupload)"  %>
  <p>Wenn du möchtest, kannst du eine Datei hochladen. Nutze diese Funktion für umfangreiche Inhalte und Bilder. Solltest du sehr große Inhalte oder Videos an uns senden wollen, wende dich bitte kurz an <a href="mailto:zeitung@abimorrowland.de">zeitung@abimorrowland.de</a>, damit wir einen Austausch über eine geeignete Plattform organisieren können. Sende uns Bilder und Videos bitte immer in bestmöglicher Qualität.<p>
  <%= f.file_field :file %>
  <hr />
  <p>Stelle bitte sicher, dass alle Angaben korrekt sind. Du kannst deine Einreichung nach dem Erstellen selbst nicht mehr ändern. Reiche deinen Inhalt bitte erneut ein, wenn du einen Fehler gemacht hast.</p>
  <%= f.button :submit, raw("Einreichen &raquo;"), class: 'btn-primary' %>
<% end %>

app/views/contents/new_association.html.erb
<%= simple_form_for @association, url: create_content_association_path, method: :post, :html => { :multipart => true } do |f| %>
  <%= f.association :profile, label: "Profil", label_method: lambda { |profile| "#{profile.full_name}" } %>  <hr />
  <%= f.button :submit, raw("Verknüpfen &raquo;"), class: 'btn-primary' %>
<% end %>

app/views/contents/show.html.erb
<h3><%= @content.title %> <small>(<%= @content.kind %>)</small></h3>
<p><%= @content.text %></p>
<% if @content.file.exists? %>
<p><%= link_to "Datei herunterladen", @content.file.url %></p>
<% end %>
<% if current_user.moderator? %>
<p><small>Eingereicht von <%= @content.user.full_name %> (<%= mail_to @content.user.email, "Rückfrage senden", subject: "[Rückfrage] abimorrownet: Inhalt " + @content.id.to_s + " (" + @content.title + ")", body: "Hallo #{@content.user.first_name},\n\nbezüglich deiner Einreichung " + @content.title + " in abimorrownet würde ich gerne eine Rückfrage an dich richten:\n\nDu kannst deine Einreichung unter " + content_url(@content) + " ansehen und ändern. Vielen Dank für deine Mithilfe.\n\nViele Grüße\n" + current_user.first_name + " " + current_user.last_name %>).</small></p>
<% end %>
<hr />
<h3>Profilassoziationen</h3>
<small>(zum Entfernen anklicken)</small>
<ul>
<% @content.content_associations.each do |assoc| %>
  <li><%= link_to assoc.profile.full_name, destroy_content_association_path(@content, assoc), method: :delete %></li>
<% end %>
</ul>
<% if current_user.moderator? %><%= link_to "Assoziation hinzufügen", new_content_association_path(@content), class: 'btn btn-success' %><% end %>
<hr />
<h3>Inhalteprobleme</h3>
<ul>
<% @content.content_problems.each do |problem| %>
  <li><%= link_to problem.reason, problem %></li>
<% end %>
</ul>
<hr />
<% if current_user.moderator? || @content.user == current_user %><%= link_to "Inhalt bearbeiten", edit_content_path(@content) %><% end %> | <%= render partial: 'admin/deletable', locals: {model_name: "Inhalt", path: content_path(@content), hide_ruler: true} %>