config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  get "intro" => "home#intro", as: :intro

  resources :profiles do
    resources :quotes
  end
  resources :committees
  resources :groups
  resources :teachers do
    resources :quotes
  end

  resources :announcements

  resources :votings do
    resources :voting_options
    resources :votes
    resources :awards do
      resources :nominations
    end
  end
  
  resources :content_problems
  
  resources :questions do
    resources :answers
  end

  resources :products
  resources :orders do
    resource :ticket
  end
  post "orders/shipping" => "orders#shipping", as: :order_shipping
  patch "orders/:id/paid" => "orders#paid", as: :mark_order_as_paid
  
  get "orders/:token/delivery" => "orders#delivery", as: :plan_delivery
  get "orders/:token/delivery/invalid" => "orders#invalid_delivery", as: :invalid_delivery
  get "orders/:token/delivery/success" => "orders#delivery_success", as: :delivery_success
  post "orders/:token/delivery" => "orders#save_delivery", as: :create_delivery_address

   
  resources :tickets

  get "tickets/info/delegate" => "tickets#delegate", as: :delegate_ticket

  resources :contents

  get "votings/:voting_id/voting_options/:option_id/select" => "voting_options#select", as: :select_voting_option
  get "votings/:voting_id/voting_options/:option_id/deselect" => "voting_options#deselect", as: :deselect_voting_option
  get "votings/:voting_id/votes/:vote_id/lock" => "votes#lock", as: :lock_vote
  get "votings/:voting_id/votes/new/selective/:max_choices" => "votes#new_selection", as: :new_selective_votes
  get "votings/:voting_id/results" => "votings#results", as: :voting_results
  delete "votings/:voting_id/cleanup" => "voting_options#cleanup", as: :cleanup_voting

  get "votings/:voting_id/awards/:award_id/nominate" => "awards#nominate", as: :nominate_for_awards

  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/accept" => "nominations#accept", as: :accept_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/dismiss" => "nominations#dismiss", as: :dismiss_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/reset" => "nominations#reset", as: :reset_nomination

  get "notifications/:user_id/stop/:stop_key" => "users#stop_notifications", as: :stop_notifications

  get "votes/validate" => "votes#validate_vote", as: :vote_validation
  post "votes/validate" => "votes#validate", as: :validate_vote

  get "contents/new/thanks" => "contents#complete", as: :content_complete

  delete "users/:id" => "users#destroy", as: :user

  get "quotes/approve" => "quotes#show_pending", as: :pending_quotes

  get "eintragen" => "student_registration#new"
  post "eintragen" => "student_registration#create"
  get "eintragen/abgeschlossen" => "student_registration#finished", as: :finished_registration

  post "profiles/:profile_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_profile_quote
  post "teachers/:teacher_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_teacher_quote

  patch "profiles/:profile_id/quotes/:quote_id/edit" => "quotes#update", as: :update_profile_quote

  get "committees/:id/participate" => "committees#prepare_participation", as: :prepare_participation
  post "committees/:id/participate" => "committees#participate", as: :participate
  delete "committees/:id/participate" => "committees#departicipate", as: :departicipate

  post "users/identity/disassociate" => "users#remove_association", as: :remove_association
  get "users/invited" => "users#list_invited", as: :invited_users
  get "users/become" => "users#become", as: :become_user
  post "users/become" => "users#become_user", as: :sign_in_as_user
  
  get "validations/:token" => "validations#index", as: :main_validations
  get "validations/:token/comments" => "validations#comments", as: :validate_comments
  get "validations/:token/contents" => "validations#contents", as: :validate_contents
  get "validations/:token/questions" => "validations#questions", as: :validate_questions
  get "validations/:token/contents/:content_id/report" => "validations#report_content", as: :report_content
  post "validations/:token/contents/:content_id/report" => "validations#create_report", as: :create_content_problem
  
  get "validations/:token/questions/:question_id/answers/new" => "validations#new_answer", as: :new_validation_answer
  get "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#edit_answer", as: :edit_validation_answer
  patch "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#update_answer", as: :update_validation_answer
  post "validations/:token/questions/:question_id/answers/new" => "validations#create_answer", as: :create_validation_answer
  
  post "validations/:token/quick_order" => "validations#quick_order", as: :create_quick_order
  
  get "validations/:token/final" => "validations#final", as: :validation_final
  get "validations/:token/preview" => "validations#preview", as: :validation_preview
  
  post "content_problems/:id/accept" => "content_problems#accept", as: :accept_report
  get "content_problems/:id/reject" => "content_problems#prepare_rejection", as: :prepare_report_rejection
  post "content_problems/:id/reject" => "content_problems#reject", as: :reject_report
  
  post "validations/:token/change_name" => "validations#change_name", as: :validation_change_name
  
  patch "validations/:token/comments/:comment_id/lock" => "validations#lock_comment", as: :lock_comment
  get "tokens" => "validations#access_tokens", as: :access_tokens
  post "tokens/new" => "validations#create_single_token", as: :create_single_token
  get "validations/:token/wrong_identity" => "validations#wrong_identity", as: :validation_wrong_identity
  get "validations/:token/error" => "validations#fatal_error", as: :validation_error
  get "validations/:token/invalid" => "validations#invalid", as: :invalid_token
  
  get "contents/:content_id/association/new" => "contents#new_association", as: :new_content_association
  post "contents/:content_id/association/new" => "contents#create_association", as: :create_content_association
  delete "contents/:content_id/association/:assoc_id" => "contents#destroy_association", as: :destroy_content_association
  
  get "tickets/orders/new" => "tickets#new_order", as: :new_ticket_order
  get "tickets/:id/download" => "tickets#download", as: :download_ticket

end

app/models/voting.rb
class Voting < ActiveRecord::Base
  has_many :voting_options
  has_many :votes
  has_many :awards

  validates :title, :start_time, :end_time, presence: true

  scope :active, -> { where('end_time > ? AND start_time < ?', DateTime.now, DateTime.now) }
  scope :finished, -> { where('end_time > ?', DateTime.now) }

  def count_users
    results = []
    self.votes.each do |vote|
      if vote.locked then
        vote.voting_options.each do |option|
          (results[option.user_id] += 1) rescue (results[option.user_id] = 1)
        end
      end
    end

    results_refac = []

    results.each_with_index do |result, index|
      if result then
        results_refac << [index, result]
      end
    end

    return results_refac.sort_by{|e| -e[1]}
  end

  def active?
    self.end_time > DateTime.now && self.start_time < DateTime.now rescue true
  end

  def finished?
    self.end_time < DateTime.now rescue true
  end
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_profile!

  respond_to :html, :json

  def index
    @votings = Voting.all
  end

  def new
    authorize :votings, :new?
  end

  def create
    authorize :votings, :create?

    if @voting = Voting.create(voting_params)
      redirect_to @voting
    else
      flash[:notice] = "Ein Fehler ist aufgetreten. Bitte prüfe deine Eingabe."
      render :new
    end
  end

  def show
    @voting = Voting.find(params[:id])
    if @voting.election? then
      @results = @voting.count_users
      @awards = @voting.awards
    end
    @all_votes = @voting.votes
    @locked_votes = 0
    @all_votes.where(locked: true).each do |vote|
      @locked_votes += vote.voted_options.count
    end

    @participation = @all_votes.where(locked: true).count.to_f / @all_votes.count.to_f
  end

  def edit
    authorize :votings, :edit?

    @voting = Voting.find(params[:id])
  end

  def update
    @voting = Voting.find(params[:id])
    authorize @voting

    if @voting.update(voting_params)
      redirect_to @voting
    else
      render :edit
    end
  end

  def results
    @voting = Voting.find(params[:voting_id])
    authorize @voting

    @results = @voting.voting_options
    if @voting.election?
      @results = @voting.count_users
      @label = []
      @series = []
      @results.each do |resultset|
        @label << User.find(resultset[0]).full_name
        @series << resultset[1]
      end
    else
      @label = @results.pluck(:title)
      @series = []
      @results.each do |option|
        @series << option.votes.where(locked: true).count
      end
    end

    respond_to do |format|
      format.html { render json: {labels: @label, series: [@series]} }
      format.json { render json: {labels: @label, series: [@series]} }
    end
  end

  def voting_params
    params.require(:voting).permit(:title, :description, :start_time, :end_time, :election, :interactive, :premium)
  end
end

app/helpers/votings_helper.rb
module VotingsHelper
end

app/views/votings/_voting_list_entry.html.erb
<tr>
  <td><%= voting.title %></td>
  <td><%= voting.active? ? "Ja" : "Nein" %></td>
  <td><%= link_to raw("Ansehen &raquo;"), voting %></td>
</tr>

app/views/votings/edit.html.erb
<h2>Abstimmung bearbeiten</h2>
<%= simple_form_for(@voting, method: :patch) do |f| %>
  <%= f.input :title, label: 'Titel der Abstimmung' %>
  <%= f.input :start_time, as: :datetime, label: "Beginn der Abstimmung (wenigstens 30min in der Zukunft)" %>
  <%= f.input :end_time, as: :datetime, label: "Ende der Abstimmung" %>
  <%= f.input :description, as: :text, label: "Beschreibung"  %>
  <%= f.input :interactive, as: :boolean, label: "Vorschläge erlauben?" %>
  <%= f.input :premium, as: :boolean, label: "Ergebnisse nur Premium-Nutzern anzeigen?" %>
  <%= f.button :submit, "Speichern" %>
  <% end %>

app/views/votings/index.html.erb
<h3>Laufende Abstimmungen</h3>
<table class="table table-striped table-bordered">
  <thead>
    <th>Titel</th>
    <th>aktiv?</th>
    <th>Aktion</th>
  </thead>
  <tbody>
    <%= render partial: 'voting_list_entry', collection: @votings, as: :voting %>
  </tbody>
</table>
<p><%= link_to "Stimme überprüfen", vote_validation_path %></p>
<% unless current_user.votes.empty? %><p>Im <%= link_to 'Dashboard', root_url %> liegen Wahlkarten für dich bereit.</p><% end %>
<%= render partial: 'admin/creatable', locals: {model_name: "Abstimmung", path: new_voting_path, hide_ruler: false} %>

app/views/votings/new.html.erb
<%= simple_form_for :voting, url: {action: 'create'}, :html => { :multipart => true } do |f| %>
<h3>Abstimmung erstellen</h3>
<%= f.input :title, label: 'Titel der Abstimmung' %>
<%= f.input :start_time, as: :datetime, label: "Beginn der Abstimmung (wenigstens 30min in der Zukunft)" %>
<%= f.input :end_time, as: :datetime, label: "Ende der Abstimmung" %>
<%= f.input :description, as: :text, label: "Beschreibung"  %>
<p>Wähle das nachfolgende Feld aus, wenn du eine Award-Wahl oder eine andere Art von Wahl, bei der SchülerInnen gewählt werden können, starten willst. Du kannst dann keine Optionen hinzufügen.</p>
<%= f.input :election, as: :boolean, label: "Wahl?" %>
<%= f.input :interactive, as: :boolean, label: "Vorschläge erlauben?" %>
<%= f.input :premium, as: :boolean, label: "Ergebnisse nur Premium-Nutzern anzeigen?" %>
  <hr />
  <p>Nach dem Anlegen der Abstimmung kannst du Optionen hinzufügen und Wahlkarten erstellen.</p>
  <%= f.button :submit, raw("Erstellen &raquo;"), class: 'btn-primary' %>
  <% end %>

app/views/votings/show.html.erb
<h2><%= @voting.title %></h2>
<p><%= @voting.description %></p>
<p>Startzeitpunkt: <%= @voting.start_time.strftime('%d.%m.%Y um %H:%M Uhr') rescue "???" %> | Endzeitpunkt: <%= @voting.end_time.strftime('%d.%m.%Y um %H:%M Uhr') rescue "???" %></p>
<% if @voting.election? %>
<span class="label label-primary">Wahl</span>
<% else %>
<span class="label label-default">Optionsabstimmung</span>
<% end %>
<% if current_user.admin? %>
<h3>Optionen</h3>
<ul>
  <% if @voting.election? %>
  <% @results.each do |result_set|
      user = User.find(result_set[0]) %>
  <li><%= link_to user.full_name, profile_path(user.profile) %> - <%= result_set[1] %> Stimme(n)</li>
  <% end %>
  <% else
  @voting.voting_options.each do |option| %>
  <li><%= link_to option.title, voting_voting_option_path(@voting, option), method: :delete, data: { confirm: "Möchtest du diese Option löschen?"} %> - <%= option.votes.where(locked: true).count %> Stimme(n)</li><% end %>
  <% end %>
</ul>
<p>(<%= @locked_votes %> Stimme(n) insgesamt, <%= @participation * 100 %> % Stimmbeteiligung)</p>
<%= unless @voting.election? then link_to  raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Neue Option'), new_voting_voting_option_path(@voting.id), class: 'btn btn-success btn-sm' end %>
<%= if @voting.election? then link_to  "Aufräumen", cleanup_voting_path(@voting), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: "Bist du sicher? Wenn du fortfährst, werden alle Optionen mit 0 Stimmen gelöscht." } end %>
<% end %>
<% if policy(@voting).results? && @voting.election? %>
<div class="ct-chart" style="height: <%= "#{@voting.count_users.size * 35}px" %>"></div>
<% end %>
<% if current_user.admin? %>
<h2>Stimmkarten</h2>
<p><%= @voting.votes.count %> Stimmkarte(n) sind mit dieser Abstimmung verknüpft. <%= link_to raw("Alle verknüpften Stimmkarten ansehen &raquo;"), voting_votes_path(@voting) %></p>
<%= link_to "Stimmkarten versenden", new_voting_vote_path(@voting.id) %>
<% else if @voting.active? %>
<p>Sobald die Abstimmung abgeschlossen ist, kannst du hier die Ergebnisse sehen. Wenn du an dieser Abstimmung teilnehmen möchtest, rufe deine Stimmkarte über das <%= link_to "Dashboard", root_url %> auf.</p>
<% end %>
<% end %>
<% if policy(@voting).results? %>
<hr />
<h2>Auszeichnungen</h2>
<% if @awards then %>
<ul>
  <% @awards.each do |award| %>
  <li><%= link_to award.title, [@voting, award] %></li>
  <% end %>
</ul>
<% end %>
<% end %>
<% if current_user.admin? then %>
<%= if @voting.election? then link_to  raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Neue Auszeichnung'), new_voting_award_path(@voting.id), class: 'btn btn-success btn-sm' end %>
<% end %>
<%= render partial: 'admin/editable', locals: {model_name: "Abstimmung", path: edit_voting_path(@voting), hide_ruler: false} %>