config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  get "intro" => "home#intro", as: :intro

  resources :profiles do
    resources :quotes
  end
  resources :committees
  resources :groups
  resources :teachers do
    resources :quotes
  end

  resources :announcements

  resources :votings do
    resources :voting_options
    resources :votes
    resources :awards do
      resources :nominations
    end
  end
  
  resources :content_problems
  
  resources :questions do
    resources :answers
  end

  resources :products
  resources :orders do
    resource :ticket
  end
  post "orders/shipping" => "orders#shipping", as: :order_shipping
  patch "orders/:id/paid" => "orders#paid", as: :mark_order_as_paid
  
  get "orders/:token/delivery" => "orders#delivery", as: :plan_delivery
  get "orders/:token/delivery/invalid" => "orders#invalid_delivery", as: :invalid_delivery
  get "orders/:token/delivery/success" => "orders#delivery_success", as: :delivery_success
  post "orders/:token/delivery" => "orders#save_delivery", as: :create_delivery_address

   
  resources :tickets

  get "tickets/info/delegate" => "tickets#delegate", as: :delegate_ticket

  resources :contents

  get "votings/:voting_id/voting_options/:option_id/select" => "voting_options#select", as: :select_voting_option
  get "votings/:voting_id/voting_options/:option_id/deselect" => "voting_options#deselect", as: :deselect_voting_option
  get "votings/:voting_id/votes/:vote_id/lock" => "votes#lock", as: :lock_vote
  get "votings/:voting_id/votes/new/selective/:max_choices" => "votes#new_selection", as: :new_selective_votes
  get "votings/:voting_id/results" => "votings#results", as: :voting_results
  delete "votings/:voting_id/cleanup" => "voting_options#cleanup", as: :cleanup_voting

  get "votings/:voting_id/awards/:award_id/nominate" => "awards#nominate", as: :nominate_for_awards

  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/accept" => "nominations#accept", as: :accept_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/dismiss" => "nominations#dismiss", as: :dismiss_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/reset" => "nominations#reset", as: :reset_nomination

  get "notifications/:user_id/stop/:stop_key" => "users#stop_notifications", as: :stop_notifications

  get "votes/validate" => "votes#validate_vote", as: :vote_validation
  post "votes/validate" => "votes#validate", as: :validate_vote

  get "contents/new/thanks" => "contents#complete", as: :content_complete

  delete "users/:id" => "users#destroy", as: :user

  get "quotes/approve" => "quotes#show_pending", as: :pending_quotes

  get "eintragen" => "student_registration#new"
  post "eintragen" => "student_registration#create"
  get "eintragen/abgeschlossen" => "student_registration#finished", as: :finished_registration

  post "profiles/:profile_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_profile_quote
  post "teachers/:teacher_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_teacher_quote

  patch "profiles/:profile_id/quotes/:quote_id/edit" => "quotes#update", as: :update_profile_quote

  get "committees/:id/participate" => "committees#prepare_participation", as: :prepare_participation
  post "committees/:id/participate" => "committees#participate", as: :participate
  delete "committees/:id/participate" => "committees#departicipate", as: :departicipate

  post "users/identity/disassociate" => "users#remove_association", as: :remove_association
  get "users/invited" => "users#list_invited", as: :invited_users
  get "users/become" => "users#become", as: :become_user
  post "users/become" => "users#become_user", as: :sign_in_as_user
  
  get "validations/:token" => "validations#index", as: :main_validations
  get "validations/:token/comments" => "validations#comments", as: :validate_comments
  get "validations/:token/contents" => "validations#contents", as: :validate_contents
  get "validations/:token/questions" => "validations#questions", as: :validate_questions
  get "validations/:token/contents/:content_id/report" => "validations#report_content", as: :report_content
  post "validations/:token/contents/:content_id/report" => "validations#create_report", as: :create_content_problem
  
  get "validations/:token/questions/:question_id/answers/new" => "validations#new_answer", as: :new_validation_answer
  get "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#edit_answer", as: :edit_validation_answer
  patch "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#update_answer", as: :update_validation_answer
  post "validations/:token/questions/:question_id/answers/new" => "validations#create_answer", as: :create_validation_answer
  
  post "validations/:token/quick_order" => "validations#quick_order", as: :create_quick_order
  
  get "validations/:token/final" => "validations#final", as: :validation_final
  get "validations/:token/preview" => "validations#preview", as: :validation_preview
  
  post "content_problems/:id/accept" => "content_problems#accept", as: :accept_report
  get "content_problems/:id/reject" => "content_problems#prepare_rejection", as: :prepare_report_rejection
  post "content_problems/:id/reject" => "content_problems#reject", as: :reject_report
  
  post "validations/:token/change_name" => "validations#change_name", as: :validation_change_name
  
  patch "validations/:token/comments/:comment_id/lock" => "validations#lock_comment", as: :lock_comment
  get "tokens" => "validations#access_tokens", as: :access_tokens
  post "tokens/new" => "validations#create_single_token", as: :create_single_token
  get "validations/:token/wrong_identity" => "validations#wrong_identity", as: :validation_wrong_identity
  get "validations/:token/error" => "validations#fatal_error", as: :validation_error
  get "validations/:token/invalid" => "validations#invalid", as: :invalid_token
  
  get "contents/:content_id/association/new" => "contents#new_association", as: :new_content_association
  post "contents/:content_id/association/new" => "contents#create_association", as: :create_content_association
  delete "contents/:content_id/association/:assoc_id" => "contents#destroy_association", as: :destroy_content_association
  
  get "tickets/orders/new" => "tickets#new_order", as: :new_ticket_order
  get "tickets/:id/download" => "tickets#download", as: :download_ticket

end

app/views/notifications/_announcement.html.erb
<strong><%= announcement.title %></strong>
<p><%= announcement.text %></p>
<% unless announcement.file.empty? %>
<%= link_to raw("<span class='glyphicon glyphicon-download' aria-hidden='true'></span> Datei herunterladen"), announcement.file, class: 'btn btn-sm btn-default' %>
<% end %>
<%= render partial: 'admin/deletable', locals: {model_name: "Ankündigung", path: announcement, hide_ruler: true} %>
<%= render partial: 'admin/editable', locals: {model_name: "Ankündigung", path: edit_announcement_path(announcement), hide_ruler: true} %>
<hr />

app/views/notifications/_announcements.html.erb
<div id="announcements">
<% unless @announcements.empty? %>
<%= render partial: 'notifications/announcement', collection: @announcements, as: :announcement %>
<% end %>
<%= render partial: 'admin/creatable', locals: {model_name: "Ankündigung", path: new_announcement_path, hide_ruler: true} %>
</div>

app/views/notifications/_my_committees.html.erb
<li><%= link_to committee.title, committee %></li>

app/views/notifications/_no_group.html.erb
<% unless current_user.group %>
<div class="alert alert-warning"><p><b>Kein Seminarfach: </b>Du bist derzeit keinem Seminarfach zugeordnet. Bitte ordne dich <%= link_to "hier", edit_profile_path(current_user.profile) %> deinem Seminarfach zu, da du sonst nicht an Diskussionen und Abstimmungen teilnehmen kannst.</p></div>
<% end %>

app/views/notifications/_nominations.html.erb
<li><%= link_to "#{nomination.award.title}", [nomination.award.voting, nomination.award, nomination] %> - <b><%= nomination.accepted ? "angenommen": "nicht angenommen" %></b></li>

app/views/notifications/_quotes_to_approve.html.erb
<% if @quotes_pending %>
<div class="alert alert-info">
<p>Es gibt <%= @pending_quotes.size %> Kommentar(e), die <%= link_to "auf Freigaben warten", pending_quotes_path %>.</p>
</div>
<% end %>

app/views/notifications/_votes.html.erb
<% if vote.voting.active? %>
<li><%= link_to "#{vote.voting.title} (Wahlkartennr.: #{vote.uid})", voting_vote_path(vote.voting, vote) %> - gültig bis zum <%= vote.voting.end_time.strftime("%d.%m.%Y um %H:%M Uhr") rescue "???" %></li>
<% end %>