config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  get "intro" => "home#intro", as: :intro

  resources :profiles do
    resources :quotes
  end
  resources :committees
  resources :groups
  resources :teachers do
    resources :quotes
  end

  resources :announcements

  resources :votings do
    resources :voting_options
    resources :votes
    resources :awards do
      resources :nominations
    end
  end
  
  resources :content_problems
  
  resources :questions do
    resources :answers
  end

  resources :products
  resources :orders do
    resource :ticket
  end
  post "orders/shipping" => "orders#shipping", as: :order_shipping
  patch "orders/:id/paid" => "orders#paid", as: :mark_order_as_paid
  
  get "orders/:token/delivery" => "orders#delivery", as: :plan_delivery
  get "orders/:token/delivery/invalid" => "orders#invalid_delivery", as: :invalid_delivery
  get "orders/:token/delivery/success" => "orders#delivery_success", as: :delivery_success
  post "orders/:token/delivery" => "orders#save_delivery", as: :create_delivery_address

   
  resources :tickets

  get "tickets/info/delegate" => "tickets#delegate", as: :delegate_ticket

  resources :contents

  get "votings/:voting_id/voting_options/:option_id/select" => "voting_options#select", as: :select_voting_option
  get "votings/:voting_id/voting_options/:option_id/deselect" => "voting_options#deselect", as: :deselect_voting_option
  get "votings/:voting_id/votes/:vote_id/lock" => "votes#lock", as: :lock_vote
  get "votings/:voting_id/votes/new/selective/:max_choices" => "votes#new_selection", as: :new_selective_votes
  get "votings/:voting_id/results" => "votings#results", as: :voting_results
  delete "votings/:voting_id/cleanup" => "voting_options#cleanup", as: :cleanup_voting

  get "votings/:voting_id/awards/:award_id/nominate" => "awards#nominate", as: :nominate_for_awards

  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/accept" => "nominations#accept", as: :accept_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/dismiss" => "nominations#dismiss", as: :dismiss_nomination
  get "votings/:voting_id/awards/:award_id/nominations/:nomination_id/reset" => "nominations#reset", as: :reset_nomination

  get "notifications/:user_id/stop/:stop_key" => "users#stop_notifications", as: :stop_notifications

  get "votes/validate" => "votes#validate_vote", as: :vote_validation
  post "votes/validate" => "votes#validate", as: :validate_vote

  get "contents/new/thanks" => "contents#complete", as: :content_complete

  delete "users/:id" => "users#destroy", as: :user

  get "quotes/approve" => "quotes#show_pending", as: :pending_quotes

  get "eintragen" => "student_registration#new"
  post "eintragen" => "student_registration#create"
  get "eintragen/abgeschlossen" => "student_registration#finished", as: :finished_registration

  post "profiles/:profile_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_profile_quote
  post "teachers/:teacher_id/quotes/:quote_id/approve" => "quotes#approve", as: :approve_teacher_quote

  patch "profiles/:profile_id/quotes/:quote_id/edit" => "quotes#update", as: :update_profile_quote

  get "committees/:id/participate" => "committees#prepare_participation", as: :prepare_participation
  post "committees/:id/participate" => "committees#participate", as: :participate
  delete "committees/:id/participate" => "committees#departicipate", as: :departicipate

  post "users/identity/disassociate" => "users#remove_association", as: :remove_association
  get "users/invited" => "users#list_invited", as: :invited_users
  get "users/become" => "users#become", as: :become_user
  post "users/become" => "users#become_user", as: :sign_in_as_user
  
  get "validations/:token" => "validations#index", as: :main_validations
  get "validations/:token/comments" => "validations#comments", as: :validate_comments
  get "validations/:token/contents" => "validations#contents", as: :validate_contents
  get "validations/:token/questions" => "validations#questions", as: :validate_questions
  get "validations/:token/contents/:content_id/report" => "validations#report_content", as: :report_content
  post "validations/:token/contents/:content_id/report" => "validations#create_report", as: :create_content_problem
  
  get "validations/:token/questions/:question_id/answers/new" => "validations#new_answer", as: :new_validation_answer
  get "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#edit_answer", as: :edit_validation_answer
  patch "validations/:token/questions/:question_id/answers/:answer_id/edit" => "validations#update_answer", as: :update_validation_answer
  post "validations/:token/questions/:question_id/answers/new" => "validations#create_answer", as: :create_validation_answer
  
  post "validations/:token/quick_order" => "validations#quick_order", as: :create_quick_order
  
  get "validations/:token/final" => "validations#final", as: :validation_final
  get "validations/:token/preview" => "validations#preview", as: :validation_preview
  
  post "content_problems/:id/accept" => "content_problems#accept", as: :accept_report
  get "content_problems/:id/reject" => "content_problems#prepare_rejection", as: :prepare_report_rejection
  post "content_problems/:id/reject" => "content_problems#reject", as: :reject_report
  
  post "validations/:token/change_name" => "validations#change_name", as: :validation_change_name
  
  patch "validations/:token/comments/:comment_id/lock" => "validations#lock_comment", as: :lock_comment
  get "tokens" => "validations#access_tokens", as: :access_tokens
  post "tokens/new" => "validations#create_single_token", as: :create_single_token
  get "validations/:token/wrong_identity" => "validations#wrong_identity", as: :validation_wrong_identity
  get "validations/:token/error" => "validations#fatal_error", as: :validation_error
  get "validations/:token/invalid" => "validations#invalid", as: :invalid_token
  
  get "contents/:content_id/association/new" => "contents#new_association", as: :new_content_association
  post "contents/:content_id/association/new" => "contents#create_association", as: :create_content_association
  delete "contents/:content_id/association/:assoc_id" => "contents#destroy_association", as: :destroy_content_association
  
  get "tickets/orders/new" => "tickets#new_order", as: :new_ticket_order
  get "tickets/:id/download" => "tickets#download", as: :download_ticket

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_many :committee_roles, dependent: :destroy
  has_many :users, through: :committee_roles

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_profile!

  def index
    @committees = Committee.all
  end

  def new

  end

  def edit
    authorize :committee, :edit?

    @committee = find_committee
  end

  def update
    @committee = find_committee
    authorize @committee

    @committee.assign_attributes(committee_params)
    users = User.find(params[:committee][:user_ids].reject! { |c| c.empty? })
    @committee.users = users

    if @committee.save
      redirect_to @committee
    else
      render :edit
    end
  end

  def create
    authorize :committee, :create?

    if @committee = Committee.create(committee_params)
      redirect_to @committee
    else
      redirect_to new_committee_url, alert: "Fehler beim Speichern."
    end
  end

  def show
    @committee = find_friendly(Committee.includes(users: :profile))
    authorize @committee

    @members = @committee.users rescue []
  end

  def destroy
    @committee = find_committee
    authorize @committee

    @committee.destroy
    redirect_to committees_path
  end

  def prepare_participation
    @committee = find_committee
  end

  def participate
    @committee = find_committee
    authorize @committee

    current_user.committees << @committee

    redirect_to @committee, notice: "Herzlichen Glückwunsch! Du nimmst jetzt an diesem Komitee teil."
  end

  def departicipate
    @committee = find_committee
    authorize @committee

    current_user.committees.delete(@committee)

    redirect_to @committee, notice: "Wir haben deine Mitgliedschaft beendet."
  end

  private

  def find_committee
    Committee.friendly.find(params[:id]) || Committee.find(params[:id])
  end

  def committee_params
    params.require(:committee).permit(:title, :description)
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_committee.html.erb
<div id="committee-<%= committee.id %>" class="row committee-box">
  <div class="col-md-6">
    <h3><%= committee.title %><% if current_user.committees.include?(committee) %> <span class="label label-success">Mitglied</span><% end %></h3>
    <p><%= committee.description %></p>
    <%= link_to raw("Anzeigen &raquo;"), committee_path(committee), class: 'btn btn-primary' %>
  </div>
  <div class="col-md-6">
  </div>
</div>

app/views/committees/_members.html.erb
<% if member.profile %>
<tr>
  <td><%= member.first_name %></td>
  <td><%= member.last_name %></td>
  <td><%= link_to raw("Ansehen &raquo;"), member.profile %></td>
</tr>
<% else %>
<tr>
  <td colspan="3">???</td>
</tr>
<% end %>

app/views/committees/_participate.html.erb
<% if current_user.committees.include?(@committee) %>
<%= link_to "Teilnahme beenden", departicipate_path, method: :delete, class: "btn btn-sm btn-danger", data: {confirm: "Bist du sicher? Deine Teilnahme wird sofort beendet."} %>
<% else %>
<%= link_to "Mitmachen", prepare_participation_path, class: "btn btn-sm btn-success" %>
<% end %>

app/views/committees/edit.html.erb
<h2>Komitee bearbeiten</h2>
<%= simple_form_for(@committee, method: :patch) do |f| %>
<%= f.input :title, label: "Titel" %>
<%= f.input :description, label: "Beschreibung" %>
<%= f.association :users, label_method: lambda { |item| "#{item.first_name} #{item.last_name}".html_safe rescue "#{item.email}" } %>
<%= f.button :submit, "Speichern" %>
<% end %>
<%= render partial: 'admin/deletable', locals: {model_name: "Komitee", path: @committee, hide_ruler: false} %>

app/views/committees/index.html.erb
<%
if @committees %>
<%= render partial: 'committee', collection: @committees %>
<% else %>
<p>Keine Komitees.</p>
<% end %>
<%= render partial: 'admin/creatable', locals: {model_name: "Komitee", path: new_committee_path, hide_ruler: false} %>

app/views/committees/new.html.erb
<%= simple_form_for :committee, url: {action: 'create'} do |f| %>
  <%= f.input :title, label: "Titel" %>
  <%= f.input :description, label: "Beschreibung" %>
  <%= f.button :submit %>
<% end %>

app/views/committees/prepare_participation.html.erb
<h2>Teilnahme bestätigen</h2>
<p>Wir freuen uns, dass du im Komitee "<%= @committee.title %>" mithelfen möchtest, bitten dich jedoch, nur dann deine Teilnahme zu erklären, wenn du tatsächlich bereit bist, dich an dessen Arbeit zu beteiligen.
Du kannst deine Teilnahme jederzeit beenden; bitte berücksichtige aber, dass sich das Komitee auf deine Mithilfe verlässt.</p>
<hr />
<p>Ich möchte mich an der Arbeit des Komitees beteiligen. Ich erhalte sofort den Status "Mitglied" zugewiesen.</p>
<%= link_to "Ja, wirklich teilnehmen", participate_path, method: :post, class: 'btn btn-success' %> <%= link_to "Nein, lieber nicht", root_url, class: 'btn btn-danger' %>

app/views/committees/show.html.erb
<h2><%= @committee.title %></h2>
<p><%= @committee.description %></p>
<h3>Mitglieder</h3>
<table class="table table-striped table-bordered">
  <thead>
    <th>Vorname</th>
    <th>Nachname</th>
    <th>Aktion</th>
  </thead>
  <tbody>
    <%= render partial: 'members', collection: @members, as: :member %>
  </tbody>
</table>
<%= render partial: 'participate' %>
<%= render partial: 'admin/editable', locals: {model_name: "Komitee", path: edit_committee_path(@committee), hide_ruler: false} %>